removed variable due to failed vercel deployment
Error: Error building site: failed to render pages: render of "home" failed: "/vercel/path0/themes/cactus/layouts/index.html:4:35": execute of template failed: template: index.html:4:35: executing "main" at <$.Page.RenderString>: can't evaluate field RenderString in type page.Page